spring.application.name=demo2_new

#database connection

spring.datasource.url=jbc:postgresql://localhost:5432
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
